# This is a basic workflow to help you get started with Actions

name: Bit build and Test CI - Web Components

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [main]
    paths:
      - "components/**"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bit-build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Node Modules
        run: npm install -g yarn && yarn install
      - name: Install Bit Version Manager
        run: npm i -g @teambit/bvm
      - name: Install latest Bit version
        run: bvm install
      - name: add bvm bin folder to path
        run: echo "$HOME/bin" >> $GITHUB_PATH
      - name: Set up bit config
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token $BIT_TOKEN
      - name: Copy Components to Bit
        run: node ./.scripts/copyFilesToBit
      - name: Import from Bit Remote
        run: cd ./.trailmix-bit && bit import
      - name: Install packages using bit
        run: cd ./.trailmix-bit && bit install
      - name: Compile bit packages
        run: |
          cd ./.trailmix-bit && bit compile
          cd ./.trailmix-bit && bit status
      - name: Hard-tag pending components
        run: cd ./.trailmix-bit && bit tag --persist
